[package]
name = "kaniko-compose-builder"
version = "1.0.0"
authors = ["Jonathan Krebs <jonathan.krebs@bruckbu.de>"]
edition = "2018"

[dependencies]
indexmap = { version = "*", features = ["serde-1"] }
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
anyhow = "*"
